Azure-Samples/cassandra-proxy

LICENSE.md
pom.xml
src/main/java/com/microsoft/azure/cassandraproxy/BufferCodec.java
src/main/java/com/microsoft/azure/cassandraproxy/FastDecode.java
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Initial version

---

CHANGELOG.md
CONTRIBUTING.md
src/main/java/com/microsoft/azure/cassandraproxy/FastDecode.java
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

More fixes

---

pom.xml
src/main/java/com/microsoft/azure/cassandraproxy/FastDecode.java
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/UUIDGen.java
src/main/java/com/microsoft/azure/cassandraproxy/UUIDGenWrapper.java
src/test/java/com/microsoft/azure/cassandraproxy/ProxyTest.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adds replacement for UUID() and now() in queries

---

README.md
pom.xml
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java
src/main/resources/logback.xml

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adds logging and metrics

---

README.md
pom.xml
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Docker support and bug fixes

---

README.md
src/main/java/com/microsoft/azure/cassandraproxy/Credential.java
src/main/java/com/microsoft/azure/cassandraproxy/FastDecode.java
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Substitute the prepared md5 if it differs between source and destination

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fixes a bug with metrics

---

README.md
src/main/resources/logback.xml

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adds asynchronous logging for more speed

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

the connection expires.
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adds an idle timeout and close client connections every time

---

README.md

* This change fixes some minor typos in the README.md
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```

Fix some minor typos in the README.md

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

on source but not destination for the table specified
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adds a --filter-tables to ahve operations only happen

---

src/main/java/com/microsoft/azure/cassandraproxy/BufferCodec.java
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

This introduces the ability to substitute ips in system.peers

---

README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Ghost proxy readme

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fixes issue with ghost proxy test

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

dest is down
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Closes connections faster and allows for a way to ignore when

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Replace close with async end for speed up

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

This might avoid seeing the pause/resume stuff
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Adds new parameter to control write queue size

---

src/main/java/com/microsoft/azure/cassandraproxy/FastDecode.java
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Speed up applying of the filter by disregarding query options

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Handle BATCH

---

pom.xml
src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Improves filtering and output the tables with if in target only

---

src/main/java/com/microsoft/azure/cassandraproxy/Proxy.java
src/main/java/com/microsoft/azure/cassandraproxy/ProxyClient.java

1) Prints the error and the cql whan an error is detected
on the target but not the source
2) Metrics to see how long the target and the source took
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Better target error handling + metrics
